/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446re.h"
#include "gpio.h"

#define ButtonPressed 0
#define ButtonNotPressed 1

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

static void delay(uint32_t time){

   for (int i=0;i<time;i++){
	   __asm__ volatile("nop");

   }

}



int main(void)
{
	GPIO_HANDLE GpioLed;
	GpioLed.pGPIOx = GPIOA;

	GpioLed.GPIO_pincfg.pinNumber  = 5;
	GpioLed.GPIO_pincfg.pinMode    = GPIO_OMODE;
	GpioLed.GPIO_pincfg.oputMode   = GPIO_OUTTYP_PP;
	GpioLed.GPIO_pincfg.oputSpeed  = GPIO_OSPEED_LOW ;
	GpioLed.GPIO_pincfg.pupdMode   = GPIO_NO_PHPL ;

	GPIO_PeriCLKEN(GPIOA, ENABLE);
	GPIO_Init(&GpioLed);

	GPIO_HANDLE GpioButton;
	GpioButton.pGPIOx = GPIOB;

	GpioButton.GPIO_pincfg.pinNumber  = 3;
	GpioButton.GPIO_pincfg.pinMode    = GPIO_IMODE;
	GpioButton.GPIO_pincfg.oputMode   = GPIO_OUTTYP_PP;
	GpioButton.GPIO_pincfg.oputSpeed  = GPIO_OSPEED_LOW ;
	GpioButton.GPIO_pincfg.pupdMode   = GPIO_PIN_PULLUP ;

	GPIO_PeriCLKEN(GPIOB, ENABLE);
	GPIO_Init(&GpioButton);

    while (1){

    if (GPIO_Readfrompin(GPIOB, GPIO_PIN_NO_3) == ButtonPressed){

     delay(100);
     GPIO_Writetopin(GPIOA ,GPIO_PIN_NO_5 , GPIO_PIN_RESET);
     delay(100000);
     GPIO_Writetopin(GPIOA ,GPIO_PIN_NO_5 , GPIO_PIN_SET);
     delay(100000);

    }
    else {

    	GPIO_Writetopin(GPIOA , GPIO_PIN_NO_5 , GPIO_PIN_RESET);

    }
}
}
